---
name: pterodactyl Wings Gameserver (Edge)
version: 2.1.1-dev-f7f337b
slug: pterodactyl_wings
description: Open Source Gameserver
url: https://github.com/FaserF/hassio-addons/tree/master/pterodactyl-wings
arch:
  - aarch64
  - amd64
# webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
map:
  - share:rw
ingress: true
init: false
panel_icon: mdi:controller
options:
  config_file: /share/pterodactyl/config.yml
schema:
  config_file: str
ports:
  "2022": 2022
  8080/tcp: 18080
ports_description:
  8080/tcp: "8080"
  2022/tcp: "2022"
