name: BentoPDF (Edge)
version: 0.1.1-dev-b9a8c0d
slug: bentopdf
description: Self-hosted, privacy-first PDF toolkit
url: https://github.com/FaserF/hassio-addons/tree/master/bentopdf
startup: services
arch:
  - aarch64
  - amd64
init: false
map:
  - ssl:rw
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str?
  keyfile: str?
ports:
  8035/tcp: 18035
ports_description:
  8035/tcp: Web Interface (HTTP/HTTPS)
ingress: true
ingress_port: 8035
panel_icon: mdi:file-pdf-box
