---
name: OpenSSL (Edge)
version: 2.1.1-dev-5e48281
slug: openssl
description: Generate self-signed certificates
url: https://github.com/FaserF/hassio-addons/tree/master/openssl
arch:
  - aarch64
  - amd64
map:
  - ssl:rw
init: false
options:
  website_name:
schema:
  website_name: str
